name: Build & Publish to Dynamis Latest

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to build (e.g. 0.0.0.33501)'
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Download Dalamud Latest
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore Project
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release AutoDuty/AutoDuty.csproj -p:AssemblyVersion=${{ github.ref_name }}

      - name: Rename zip to AutoDuty-bld.zip
        run: mv AutoDuty/bin/Release/AutoDuty/latest.zip AutoDuty/bin/Release/AutoDuty/AutoDuty-bld.zip

      - name: 'Upload to GitHub release'
        run: |
            gh release upload ${{github.event.release.tag_name}} AutoDuty/bin/Release/AutoDuty/AutoDuty-bld.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash

